### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by sambit985**
Comment Here group members

### CODE REVIEW

**Comment by GarimaPawar** [comment]
Go to . comment-wrapper  change the  
Border- nonr  change the none

**Comment by sambit985** [comment]
> Go to . comment-wrapper change the Border- nonr change the none

Ohh I  forgot to change this thing... Thank you  @GarimaPawar  for your review.

**Review by sambit985 — COMMENTED** [review]
Now all set

**Comment by sambit985** [comment]
Thanks

**Pull request merged**
